<svelte:head>
	<meta charset="UTF-8" />
	<title>Privacy Notice - 2077 Labs</title>
</svelte:head>

<div class="px-3 md:px-12 flex flex-col max-w-screen-lg mx-auto">
	<h1 class="text-4xl font-bold mb-8">Website Privacy Notice</h1>

	<h2 class="text-2xl font-semibold mb-4">1. Introduction</h2>
	<p class="mb-4">
		1.1 We are committed to safeguarding the privacy of our website visitors, service users,
		individual customers, and customer personnel.
	</p>
	<p class="mb-4">
		1.2 This notice applies where we are acting as a data controller with respect to the personal
		data of such persons; in other words, where we determine the purposes and means of the
		processing of that personal data.
	</p>
	<p class="mb-4">
		1.3 Our website incorporates privacy controls which affect how we will process your personal
		data. By using the privacy controls, you can specify whether you would like to receive direct
		marketing communications and limit the collection, sharing, and publication of your personal
		data. You can access the privacy controls via <a
			href="https://research.2077.xyz/privacy-controls"
			class="text-blue-600 underline">https://research.2077.xyz/privacy-controls</a
		>.
	</p>
	<p class="mb-4">
		1.4 We use cookies on our website. Insofar as those cookies are not strictly necessary for the
		provision of our website and services, we will ask you to consent to our use of cookies when you
		first visit our website.
	</p>
	<p class="mb-4">
		1.5 In this notice, "we", "us" and "our" refer to 2077 Labs. For more information about us, see
		Section 14.
	</p>

	<h2 class="text-2xl font-semibold mb-4">2. Credit</h2>
	<p class="mb-4">
		2.1 This document was created using a template from Docular (<a
			href="https://seqlegal.com/free-legal-documents/privacy-policy"
			class="text-blue-600 underline">https://seqlegal.com/free-legal-documents/privacy-policy</a
		>).
	</p>
	<p class="mb-4">
		You must retain the above credit. Use of this document without the credit is an infringement of
		copyright. However, you can purchase from us an equivalent document that does not include the
		credit.
	</p>

	<h2 class="text-2xl font-semibold mb-4">3. The Personal Data That We Collect</h2>
	<p class="mb-4">
		3.1 In this Section 3, we have set out the general categories of personal data that we process
		and, in the case of personal data that we did not obtain directly from you, information about
		the source and specific categories of that data.
	</p>
	<p class="mb-4">
		3.2 We may process data enabling us to get in touch with you ("contact data"). The contact data
		may include your name, email address, telephone number, postal address, and/or social media
		account identifiers. The source of the contact data is you and/or your employer. If you log into
		our website using a social media account, we will obtain elements of the contact data from the
		relevant social media account provider.
	</p>
	<p class="mb-4">
		3.3 We may process your website user account data ("account data"). The account data may include
		your account identifier, username, email address, account creation and modification dates,
		website settings. The primary source of the account data is you, although some elements of the
		account data may be generated by our website. If you log into our website using a social media
		account, we will obtain elements of the account data from the relevant social media account
		provider.
	</p>
	<p class="mb-4">
		3.4 We may process information contained in or relating to any communication that you send to us
		or that we send to you ("communication data"). The communication data may include the
		communication content and metadata associated with the communication. Our website will generate
		the metadata associated with communications made using the website contact forms.
	</p>
	<p class="mb-4">
		3.5 We may process data about your use of our website and services ("usage data"). The usage
		data may include your IP address, geographical location, browser type and version, operating
		system, referral source, length of visit, page views, and website navigation paths, as well as
		information about the timing, frequency, and pattern of your service use. The source of the
		usage data is our analytics tracking system.
	</p>

	<h2 class="text-2xl font-semibold mb-4">4. Purposes of Processing and Legal Bases</h2>
	<p class="mb-4">
		4.1 In this Section 4, we have set out the purposes for which we may process personal data and
		the legal bases of the processing.
	</p>
	<p class="mb-4">
		4.2 <strong>Operations</strong> - We may process your personal data for the purposes of operating
		our website, processing and fulfilling orders, providing our services, supplying our goods, generating
		invoices, bills, and other payment-related documentation, and credit control. The legal basis for
		this processing is our legitimate interests, namely the proper administration of our website, services,
		and business.
	</p>
	<p class="mb-4">
		4.3 <strong>Publications</strong> - We may process account data for the purposes of publishing such
		data on our website and elsewhere through our services in accordance with your express instructions.
		The legal basis for this processing is consent.
	</p>
	<p class="mb-4">
		4.4 <strong>Relationships and Communications</strong> - We may process contact data, account data,
		transaction data, and/or communication data for the purposes of managing our relationships, communicating
		with you (excluding direct marketing) by email, SMS, post, fax, and/or telephone, providing support
		services, and complaint handling. The legal basis for this processing is our legitimate interests,
		namely communications with our website visitors, service users, individual customers, and customer
		personnel, the maintenance of relationships, and the proper administration of our website, services,
		and business.
	</p>
	<p class="mb-4">
		4.5 <strong>Direct Marketing</strong> - We may process contact data, account data, and/or transaction
		data for the purposes of creating, targeting, and sending direct marketing communications by email,
		SMS, post, and/or fax, and making contact by telephone for marketing-related purposes. The legal
		basis for this processing is consent.
	</p>
	<p class="mb-4">
		4.6 <strong>Research and Analysis</strong> - We may process usage data and/or transaction data for
		the purposes of researching and analyzing the use of our website and services, as well as researching
		and analyzing other interactions with our business. The legal basis for this processing is our legitimate
		interests, namely monitoring, supporting, improving, and securing our website, services, and business
		generally.
	</p>
	<p class="mb-4">
		4.7 <strong>Record Keeping</strong> - We may process your personal data for the purposes of creating
		and maintaining our databases, backup copies of our databases, and our business records generally.
		The legal basis for this processing is our legitimate interests, namely ensuring that we have access
		to all the information we need to properly and efficiently run our business in accordance with this
		notice.
	</p>
	<p class="mb-4">
		4.8 <strong>Security</strong> - We may process your personal data for the purposes of security and
		the prevention of fraud and other criminal activity. The legal basis of this processing is our legitimate
		interests, namely the protection of our website, services, and business, and the protection of others.
	</p>
	<p class="mb-4">
		4.9 <strong>Insurance and Risk Management</strong> - We may process your personal data where necessary
		for the purposes of obtaining or maintaining insurance coverage, managing risks, and/or obtaining
		professional advice. The legal basis for this processing is our legitimate interests, namely the
		proper protection of our business against risks.
	</p>
	<p class="mb-4">
		4.10 <strong>Legal Claims</strong> - We may process your personal data where necessary for the establishment,
		exercise, or defense of legal claims, whether in court proceedings or in an administrative or out-of-court
		procedure. The legal basis for this processing is our legitimate interests, namely the protection
		and assertion of our legal rights, your legal rights, and the legal rights of others.
	</p>
	<p class="mb-4">
		4.11 <strong>Legal Compliance and Vital Interests</strong> - We may also process your personal data
		where such processing is necessary for compliance with a legal obligation to which we are subject
		or in order to protect your vital interests or the vital interests of another natural person.
	</p>

	<h2 class="text-2xl font-semibold mb-4">14. Data Protection Officer</h2>
	<p class="mb-4">16.1 Our data protection officer's contact details are: admin@2077.xyz.</p>
</div>
